# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 1.0.1
maven_group = cn.ksmcbrigade.rd_mh
archives_base_name = MovementHacks
mod_name = MovementHacks(Rd-132211)
mod_id = mh
mod_description=Fuck rd-132211!
mod_license=CC0-1.0
mod_authors=commonplace

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = a1.0.1_01
loader_version = 0.17.3

feather_build = 26
